[mypy]

[mypy-torch.*]
ignore_missing_imports = True
[mypy-torchvision.*]
ignore_missing_imports = True
[mypy-tensorflow.*]
ignore_missing_imports = True
[mypy-keras.*]
ignore_missing_imports = True
[mypy-jax.*]
ignore_missing_imports = True
[mypy-flax.*]
ignore_missing_imports = True
[mypy-transformers.*]
ignore_missing_imports = True
[mypy-datasets.*]
ignore_missing_imports = True
